// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Sidebar from "./_components/layout/Sidebar";
// import Topbar from "./_components/layout/Topbar";
// import Footer from "./_components/layout/Footer";
// import { Toaster } from "react-hot-toast";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body cz-shortcut-listen="true">
//         <div className="flex h-screen text-black overflow-hidden">
//           {/* Sidebar */}
//           <Sidebar />

//           {/* Main content */}
//           <div className="flex flex-col flex-1">
//             <Topbar />

//             <main className="flex-1 bg-[#F8F8F8] overflow-x-hidden overflow-y-auto  p-2  ">
//               {children}
//                <Toaster position="top-center" reverseOrder={false} />
//             </main>

//             <Footer />
//           </div>
//         </div>
//       </body>
//     </html>
//   );
// }



// the above code is working






// /app/layout.tsx
"use client";

import { useEffect, useState } from "react";
import { useRouter, usePathname } from "next/navigation";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./_components/layout/Sidebar";
import Topbar from "./_components/layout/Topbar";
import Footer from "./_components/layout/Footer";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Since we're using "use client", remove metadata export
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Kisan Dashboard</title>
        <meta name="description" content="Kisan Partner Dashboard" />
      </head>
      <body cz-shortcut-listen="true" className={`${geistSans.variable} ${geistMono.variable}`}>
        <AuthWrapper>
          {children}
          <Toaster position="top-center" reverseOrder={false} />
        </AuthWrapper>
      </body>
    </html>
  );
}

// Separate component for authentication logic
function AuthWrapper({ children }: { children: React.ReactNode }) {
  const [loading, setLoading] = useState(true);
  const [authenticated, setAuthenticated] = useState(false);
  const router = useRouter();
  const pathname = usePathname();

  // Check if current route is public
  const isPublicRoute = pathname === '/admin/login' || 
                       pathname === '/login' || 
                       pathname === '/';

  useEffect(() => {
    // Only check auth for protected routes
    if (!isPublicRoute) {
      checkAuth();
    } else {
      setLoading(false);
    }
  }, [pathname]);

  const checkAuth = async () => {
    try {
      const response = await fetch("/api/admin/session");
      if (response.ok) {
        const data = await response.json();
        if (data.success) {
          setAuthenticated(true);
        } else {
          router.push("/admin/login");
        }
      } else {
        router.push("/admin/login");
      }
    } catch (error) {
      console.error("Auth check failed:", error);
      router.push("/admin/login");
    } finally {
      setLoading(false);
    }
  };

  // Show loading spinner while checking authentication
  if (loading && !isPublicRoute) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-green-600"></div>
      </div>
    );
  }

  // For public routes, show content directly
  if (isPublicRoute) {
    return <>{children}</>;
  }

  // For protected routes, show the full layout
  return (
    <div className="flex h-screen text-black overflow-hidden">
      {/* Sidebar */}
      <Sidebar />

      {/* Main content */}
      <div className="flex flex-col flex-1">
        <Topbar />

        <main className="flex-1 text-black bg-[#F8F8F8] overflow-x-hidden overflow-y-auto p-2">
          {children}
        </main>

        <Footer />
      </div>
    </div>
  );
}